### ISSUE TITLE
Return key does not work when inputting values

### ISSUE THREAD

**Issue by stolendata** [Kalroth/cgminer-3.7.2-kalroth#7]
Running the latest version from 2014-01-30 on Win 7/64, pressing [G]PU and going into any submenu such as [I], [A], [X], [C] etc. will as usual prompt you to enter a GPU to change settings for, but the prompt does not react to the enter key. Values can be entered, but there is no way to proceed (or escape) from the prompt except terminating cgminer.

**Comment by Kalroth** [comment]
I cannot reproduce this issue.

Pressing [G]PU, then [x]Intensity, then I type 1 as GPU number, press enter, type 300 number, press enter. The xintensity is set for the GPU and I get the menu option back and can return to normal view with another enter press.

**Comment by stolendata** [comment]
Could it perhaps be that the version of ncurses you are linking against reacts to my specific console settings? ckolivas' cgminer 3.7.2 build works just fine on my machine.

color 17
mode 80,42
cd &lt;some path&gt;
setx GPU_MAX_BLAH 100
cgminer.exe ...

**Comment by Kalroth** [comment]
I'd be surprised if either color or mode had anything to do with your enter key not working, but you can always try without those settings and see if it changes anything. I asked around and I've yet to find anyone with the same issue, so I'm convinced it's a local issue.

Are you using any kind of remote software? I think I read that VNC had issues mapping enter to return, the latter doesn't seem to work in cgminer.

**Comment by Thirtybird** [comment]
I can duplicate this - sort of.  If I use the enter key on my numeric keypad, it doesn't recognize it.  If I use the regular keyboard enter key, it works just fine.  They may have different keycodes, but this has been the behaviour of every cgminer I've ever used.

**Comment by veox** [comment]
This has been reported with sgminer, too, several times. No one bothered to file a bug report and mention what exact version they're using (which binary), so there's no reference.

Enter keys on a full keyboard do have separate keycodes.

**Comment by Kalroth** [comment]
Yeah, it seems like it's intended functionality, see this stack overflow posting: http://stackoverflow.com/questions/2963317/key-enter-vs-n

The proper workaround is to use the return key. The function curses_input() in cgminer.c will need a rewrite before the keypad enter key will work, and it's pretty low priority on things I want to spend my time on.

**Comment by carly200** [comment]
Hi, I might have posted in the forums and probably did not leave enough details.

The problem occurs when remoting into windows with tightVNC, possibly because it uses Linfeed-Retun and Numpad-Enter as the same keycode.
since I remote into all my machines, this is a big headache ;-)
faulty guy seems thightVNC that probably maps both keys in the same way, but why does it work with the original 3.7.2 release?

When using the Windows on screen keyboard and clicking "linefeed", sgminer/cgminer will accept the input.
maybe there is a workaround possible to use an alternative to enter-key as well? e.g. F12

I am using Win7-64bit,
it works in the original cgminer 3.7.2 built!
it does not work in sgminer 4.0.0 (win 32 built posted in reddit)
it does not work in sgminer 4.xxx (built by wold, posted in the litecointalk thread, no better version info available)
it does not work in 4.1 64bit bye "cyper punk"

does this depend on the compiler? or is this a pure "software issue" (will check the link po

known workaround:
current nasty workaround is the on-screen-keyboard in windows ;-)

**Comment by Kalroth** [comment]
I got no idea why it doesn't work with TightVNC, nor why it works with cgminer 3.7.2. I haven't [knowingly] changed that part of the code, nor do I think sgminer has. Maybe you used an older version ot TightVNC and it broke in the meanwhile?

But seeing as I'm not about to rewrite the cgminer input code because of a defective external application, your best bet would probably be with the TightVNC developers.

Google found this open issue for me: http://sourceforge.net/p/vnc-tight/bugs/1074/

**Comment by carly200** [comment]
I saw that issue before, that is why I suggested, that it is a tightVNC anomaly. but since very many people use it, it affects mining.

I used the same version of tightVNC for months now and i just start both miners (original, sgminer, edit: just tried yours as well), it works in the original one, and does not in yours and sgminer.
so something must have changed

Your respond sounds a lot like "i don't care" to me. and if you don't have time to tinker around with it, that is ok. you make it sound as using the "other" return key is for weirdos... 

If it is not a bug (in your oppinion) than at least it is a missing feature for everyone remoting into their windows machines...
(i need to use windows as long as there is no voltage control for the 290s)

A fix could be to accepting different types of return keys....

I am trying to get setup to maybe look at this myself, unfortunateley don't have too much time fiddeling with the code yet.
but still I don't see why this is closed, it is not resolved. 

anyways, the issue should not be closed, in my opinion

**Comment by Kalroth** [comment]
My response is that it's a problem with TightVNC and not cgminer, thus there isn't anything for me to fix.

Even if I tried to fix it, I would likely end up spending hours rewriting and debugging code, trying to figure out why a single external program (that I do not even use myself) is creating issues for a few users. While doing that, I might end up creating new bugs that affects everybody, not just TightVNC users.

Until proven otherwise, the issue lies with TightVNC and the problem should be fixed there.

You can interpret that however you want.

**Comment by carly200** [comment]
yes, and you are wrong! tightVNC is probably adding to the problem

but your version and sgminer fail to accept the Enter key on the numpad, 3.7.2 does not.

**Comment by cycl0ne** [comment]
Easy workaround: Use 3.7.2. or debug yourself and create an own spinoff of cgminer. Martin is doing a great job. There could be lots of other things going wrong. are you using an own compiled 3.7.2. or are you using a binary version? perhaps this binary version was compiled with other libraries etc.

**Comment by carly200** [comment]
wow... shitty community.

the pool management also broke the pool probing. is that "not important" as well?
I found bugs and deficiencies and reported them. and all I get is knocked down for that?

also the suggestion to create a fork, just because bugs are considered minor is rediculus.
I am using 3.7.2 which works fine, but i also liked the new plain intensity settings in your builds.

I understand if somebody has lack of interest in something, especially if it creates work for him. But it should not be stated as "not my problem -> closed" if it is indeed a problem in the software.

like I said, I am trying to get setup to check code as well, but it is always easier for someone who is already familar with (parts) of the code.

Anyways, really did not like how my efforts in finding bug/problems are considered.

Can you all check if in your compiles the return-key on the num-pad works for input? if so, what libraries did you build with.
